meta_product_name: "2XL"
meta_title: "2XL - Your ideal flat as a young professional"
meta_description: "Rent your next room or apartment for a short to long-term lease online! "
meta_image: "cover.png"                       # should exist in `app/assets/images/`
